# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jasmine/Documents/git/ada-chatbot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jasmine/Documents/git/ada-chatbot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jasmine/Documents/git/ada-chatbot/CMakeFiles /home/jasmine/Documents/git/ada-chatbot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jasmine/Documents/git/ada-chatbot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ada

# Build rule for target.
ada: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ada
.PHONY : ada

# fast build rule for target.
ada/fast:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/build
.PHONY : ada/fast

interface.o: interface.c.o

.PHONY : interface.o

# target to build an object file
interface.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/interface.c.o
.PHONY : interface.c.o

interface.i: interface.c.i

.PHONY : interface.i

# target to preprocess a source file
interface.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/interface.c.i
.PHONY : interface.c.i

interface.s: interface.c.s

.PHONY : interface.s

# target to generate assembly for a file
interface.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/interface.c.s
.PHONY : interface.c.s

interpret.o: interpret.c.o

.PHONY : interpret.o

# target to build an object file
interpret.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/interpret.c.o
.PHONY : interpret.c.o

interpret.i: interpret.c.i

.PHONY : interpret.i

# target to preprocess a source file
interpret.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/interpret.c.i
.PHONY : interpret.c.i

interpret.s: interpret.c.s

.PHONY : interpret.s

# target to generate assembly for a file
interpret.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/interpret.c.s
.PHONY : interpret.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/main.c.s
.PHONY : main.c.s

parse.o: parse.c.o

.PHONY : parse.o

# target to build an object file
parse.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/parse.c.o
.PHONY : parse.c.o

parse.i: parse.c.i

.PHONY : parse.i

# target to preprocess a source file
parse.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/parse.c.i
.PHONY : parse.c.i

parse.s: parse.c.s

.PHONY : parse.s

# target to generate assembly for a file
parse.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/parse.c.s
.PHONY : parse.c.s

response.o: response.c.o

.PHONY : response.o

# target to build an object file
response.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/response.c.o
.PHONY : response.c.o

response.i: response.c.i

.PHONY : response.i

# target to preprocess a source file
response.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/response.c.i
.PHONY : response.c.i

response.s: response.c.s

.PHONY : response.s

# target to generate assembly for a file
response.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/response.c.s
.PHONY : response.c.s

score.o: score.c.o

.PHONY : score.o

# target to build an object file
score.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/score.c.o
.PHONY : score.c.o

score.i: score.c.i

.PHONY : score.i

# target to preprocess a source file
score.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/score.c.i
.PHONY : score.c.i

score.s: score.c.s

.PHONY : score.s

# target to generate assembly for a file
score.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/score.c.s
.PHONY : score.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ada"
	@echo "... edit_cache"
	@echo "... interface.o"
	@echo "... interface.i"
	@echo "... interface.s"
	@echo "... interpret.o"
	@echo "... interpret.i"
	@echo "... interpret.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... response.o"
	@echo "... response.i"
	@echo "... response.s"
	@echo "... score.o"
	@echo "... score.i"
	@echo "... score.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

