# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jasmine/Documents/git/ada-chatbot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jasmine/Documents/git/ada-chatbot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jasmine/Documents/git/ada-chatbot/CMakeFiles /home/jasmine/Documents/git/ada-chatbot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jasmine/Documents/git/ada-chatbot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ada

# Build rule for target.
ada: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ada
.PHONY : ada

# fast build rule for target.
ada/fast:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/build
.PHONY : ada/fast

src/interface.o: src/interface.c.o

.PHONY : src/interface.o

# target to build an object file
src/interface.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/interface.c.o
.PHONY : src/interface.c.o

src/interface.i: src/interface.c.i

.PHONY : src/interface.i

# target to preprocess a source file
src/interface.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/interface.c.i
.PHONY : src/interface.c.i

src/interface.s: src/interface.c.s

.PHONY : src/interface.s

# target to generate assembly for a file
src/interface.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/interface.c.s
.PHONY : src/interface.c.s

src/interpret.o: src/interpret.c.o

.PHONY : src/interpret.o

# target to build an object file
src/interpret.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/interpret.c.o
.PHONY : src/interpret.c.o

src/interpret.i: src/interpret.c.i

.PHONY : src/interpret.i

# target to preprocess a source file
src/interpret.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/interpret.c.i
.PHONY : src/interpret.c.i

src/interpret.s: src/interpret.c.s

.PHONY : src/interpret.s

# target to generate assembly for a file
src/interpret.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/interpret.c.s
.PHONY : src/interpret.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/main.c.s
.PHONY : src/main.c.s

src/parse.o: src/parse.c.o

.PHONY : src/parse.o

# target to build an object file
src/parse.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/parse.c.o
.PHONY : src/parse.c.o

src/parse.i: src/parse.c.i

.PHONY : src/parse.i

# target to preprocess a source file
src/parse.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/parse.c.i
.PHONY : src/parse.c.i

src/parse.s: src/parse.c.s

.PHONY : src/parse.s

# target to generate assembly for a file
src/parse.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/parse.c.s
.PHONY : src/parse.c.s

src/response.o: src/response.c.o

.PHONY : src/response.o

# target to build an object file
src/response.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/response.c.o
.PHONY : src/response.c.o

src/response.i: src/response.c.i

.PHONY : src/response.i

# target to preprocess a source file
src/response.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/response.c.i
.PHONY : src/response.c.i

src/response.s: src/response.c.s

.PHONY : src/response.s

# target to generate assembly for a file
src/response.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/response.c.s
.PHONY : src/response.c.s

src/score.o: src/score.c.o

.PHONY : src/score.o

# target to build an object file
src/score.c.o:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/score.c.o
.PHONY : src/score.c.o

src/score.i: src/score.c.i

.PHONY : src/score.i

# target to preprocess a source file
src/score.c.i:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/score.c.i
.PHONY : src/score.c.i

src/score.s: src/score.c.s

.PHONY : src/score.s

# target to generate assembly for a file
src/score.c.s:
	$(MAKE) -f CMakeFiles/ada.dir/build.make CMakeFiles/ada.dir/src/score.c.s
.PHONY : src/score.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ada"
	@echo "... edit_cache"
	@echo "... src/interface.o"
	@echo "... src/interface.i"
	@echo "... src/interface.s"
	@echo "... src/interpret.o"
	@echo "... src/interpret.i"
	@echo "... src/interpret.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parse.o"
	@echo "... src/parse.i"
	@echo "... src/parse.s"
	@echo "... src/response.o"
	@echo "... src/response.i"
	@echo "... src/response.s"
	@echo "... src/score.o"
	@echo "... src/score.i"
	@echo "... src/score.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

